language: php

php:
  - 7.3.5

env:
  - SYMFONY_VERSION=4.3.*

before_script:
  - composer install
  - php bin/console doctrine:schema:create --dump-sql
  - php bin/console doctrine:migrations:diff
  - php bin/console doctrine:migrations:migrate
  - php bin/console doctrine:fixtures:load 

script:
  - php bin/phpunit