language: php
php:
- 7.3.5
env:
- SYMFONY_VERSION=4.3.*
- SYMFONY_VERSION=dev-master

before_script:
- composer install
- composer require orm-fixtures --dev
- composer require --dev symfony/test-pack
- composer require --dev symfony/phpunit-bridge
- composer require --dev symfony/browser-kit symfony/css-selector
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
- php bin/console doctrine:fixtures:load -n --env=test
script:
- php bin/phpunit