language: php

php:
  - 7.3.5

services:
  - postgresql

env:
  - SYMFONY_VERSION=4.3.*

before_script:
  - composer install
  - postgresql -e "CREATE DATABASE slamquizz;CREATE ROLE slamquizz password 'i62o6CORckuM3ofQ' login;CREATE DATABASE slamquizz;"
  - php bin/console doctrine:migrations:migrate
  - php bin/console doctrine:fixtures:load 

script:
  - php bin/phpunit