language: php

php:
  - 7.3.5

services:
  - postgresql

env:
  - DATABASE_URL=pgsql://slamquizz:i62o6CORckuM3ofQ@127.0.0.1:5432/slamquizz

before_script:
  - composer install
  - psql -c "CREATE DATABASE slamquizz;" -U postgres
  - psql -c "CREATE ROLE slamquizz password 'i62o6CORckuM3ofQ' login;" -U postgres
  - psql -c "GRANT ALL ON DATABASE slamquizz TO slamquizz WITH GRANT OPTION;" -U postgres
  - php bin/console doctrine:migrations:migrate -n
  #- php bin/console doctrine:fixtures:load -n
  
script:
  - php bin/phpunit