language: php

php:
  - 7.3.5

services:
  - postgresql: "12"

env:
  - SYMFONY_VERSION=4.3.*

before_script:
  - composer install
  - psql -c "CREATE DATABASE slamquizz;" -U postgres
  - psql -c "CREATE ROLE slamquizz password 'i62o6CORckuM3ofQ' login;" -U postgres
  - psql -c "GRANT ALL ON DATABASE slamquizz TO slamquizz WITH GRANT OPTION;" -U postgres
  - php bin/console doctrine:migrations:migrate -n
  - php bin/console doctrine:fixtures:load -n
  
script:
  - php bin/phpunit